version: '3.8'

services:

  web:
    build: ./apache
    container_name: bienesraices
    ports:
      - "8080:80"
      - "2222:22"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - app-networkphp
  db:
    image: mariadb:10.6
    container_name: bienesraices_mvc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Eduardo.@
      MARIADB_DATABASE: bienesraices
      MARIADB_USER: Eduardo.@
      MARIADB_PASSWORD: 1088514H@z

    ports:
      - "3306:3306"
    volumes:
      - .www:/var/lib/mysql
    networks:
      - app-networkphp
  
  node:
    image: node:20
    container_name: node_app
    working_dir: /var/www/html
    volumes:
      - ./www:/var/www/html
    ports:
      - "3001:3000"
    command: bash

volumes:
  db_data:

networks:
  app-networkphp:


